name: CI dev

on:
  push:
    branches-ignore: 'main'
  pull_request:
    branches-ignore: 'main'
  workflow_dispatch:

jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile