name: test CI

on:
  push:
    branches: [ "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        env:
          USER: ${{ secrets.DOCKERHUB_USERNAME }}
          PAT: ${{ secrets.DOCKERHUB_PAT }}

        if: env.USER != '' && env.PAT != ''
        run: echo 'success'
